# For more information on using conda with travis see:
# http://conda.pydata.org/docs/travis.html#using-conda-with-travis-ci
# https://gist.github.com/dan-blanchard/7045057

sudo: false
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
addons:
  apt:
    packages:
      - libfreeimage-dev
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy "scikit-image>=0.11" nose
  - source activate test-environment
  - pip install mock coverage rednose codecov
  - python setup.py install
before_script:
  - "wget http://downloads.openmicroscopy.org/bio-formats/5.2.1/artifacts/bftools.zip -O /tmp/bftools.zip"
  - "unzip /tmp/bftools.zip"
  - "export PATH=$PATH:$PWD/bftools/"
# command to run tests
script: nosetests
after_success:
  codecov
