language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install numpy"
  - "pip install scipy"
  - "pip install scikit-image"
  - "pip install -r requirements.txt"
before_script:
  - wget http://downloads.openmicroscopy.org/latest/bio-formats5.1/artifacts/bftools.zip -O /tmp/bftools.zip
  - unzip /tmp/bftools.zip
  - export PATH=$PATH:$PWD/bftools/
# command to run tests
script: nosetests
